# Generated by Django 4.1 on 2023-03-04 11:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=main.models.pic_wrapper
            ),
        ),
    ]
