# Generated by Django 4.1 on 2023-03-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="carbs",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="fats",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="kcal",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="proteins",
            field=models.IntegerField(null=True),
        ),
    ]
